### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by mrquincle** [matt8707/addon-ha-fusion#2]
Leads to the following error message:

```
The command '/bin/ash -o pipefail -c npm run build --no-cache' returned a non-zero code: 1 
```

![image](https://github.com/matt8707/addon-ha-fusion/assets/1428585/1b8ec9fe-27a7-466d-be9c-ea8407102c47)

**Comment by Gwenlad** [comment]
same here.

**Comment by Gwenlad** [comment]
it's working, I don't know, I have the error message but HA fusion is in my addon page !
it's really great for a pre beta :)

**Comment by markcshaz** [comment]
Loving this and this is great for a pre-beta well done Matt

**Comment by matt8707** [comment]
Thanks!

@mrquincle can you run `ha supervisor logs` and post the full error

**Comment by matt8707** [comment]
Try 2023.12.5
