### ISSUE TITLE
"502 Bad Gateway" in user interface

### ISSUE THREAD

**Issue by Vincamok** [matt8707/addon-ha-fusion#3]
Hey,

I have an error with new version (2023.12.4) :

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
Listening on 0.0.0.0:5050
No existing file found for ./data/configuration.yaml
No existing file found for ./data/dashboard.yaml
```

I have desintall and make a new installation.

Thank you for this good dev

**Comment by matt8707** [comment]
* uninstall addon
* remove addon repo
* restart home assistant
* add repo again https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fmatt8707%2Faddon-ha-fusion
* install addon

if you still get "502 Bad Gateway" please post logs from `ha supervisor logs`

**Comment by Vincamok** [comment]
I did all the tasks one after the other.

I already have a 502 gateway error.
For your information, Home assistant is behind a reverse proxy.

```
23-12-26 14:08:10 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/matt8707/addon-ha-fusion repository
23-12-26 14:08:11 INFO (MainThread) [supervisor.store] Loading add-ons from store: 179 all - 1 new - 0 remove
23-12-26 14:08:21 INFO (MainThread) [supervisor.addons.addon] Creating Home Assistant add-on data folder /data/addons/data/65f67727_ha_fusion
23-12-26 14:08:21 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: 65f67727_ha_fusion
23-12-26 14:08:21 INFO (MainThread) [supervisor.docker.addon] Starting build for 65f67727/amd64-addon-ha_fusion:2023.12.4
23-12-26 14:08:44 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-12-26 14:08:44 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-12-26 14:08:44 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-12-26 14:10:28 INFO (MainThread) [supervisor.docker.addon] Build 65f67727/amd64-addon-ha_fusion:2023.12.4 done
23-12-26 14:10:28 INFO (MainThread) [supervisor.addons.manager] Add-on '65f67727_ha_fusion' successfully installed
23-12-26 14:11:31 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 65f67727_ha_fusion
23-12-26 14:11:33 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 65f67727/amd64-addon-ha_fusion with version 2023.12.4
```

**Comment by wraith1385** [comment]
I am  also getting this error.  I did all of the steps you listed and am still getting it.  

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
Listening on 0.0.0.0:5050
No existing file found for ./data/configuration.yaml
No existing file found for ./data/dashboard.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/dashboard.yaml`

**Comment by matt8707** [comment]
Please try 2023.12.5, also can you try without a reverse proxy to rule that out

**Comment by aleZZ2001** [comment]
same error when running outside the lan with reverse proxy

in local it works

**Comment by wraith1385** [comment]
Mine also now works if I bypass the reverse proxy.  My reverse proxy is only on my local network.

**Comment by matt8707** [comment]
Just tried nginx, don't really know how to fix it, help wanted

```
[20:35:47] INFO: Running nginx...
2023/12/27 20:47:55 [error] 142#142: *10 upstream sent too big header while reading response header from upstream, client: 192.168.1.1, server: *.duckdns.org, request: "GET /api/hassio_ingress/TUmkc7Uo51D9CWd7g46E8NpqCm4bweXlUwOunqod0yk/ HTTP/2.0", upstream: "http://172.30.32.1:8123/api/hassio_ingress/TUmkc7Uo51D9CWd7g46E8NpqCm4bweXlUwOunqod0yk/", host: "*.duckdns.org", referrer: "https://*.duckdns.org/hassio"
```

**Comment by briiiian** [comment]
The same error. And it only gets error when using https server. It's work in http.

**Comment by matt8707** [comment]
Please try addon 2023.12.8 https://github.com/matt8707/ha-fusion/commit/bd3e3cbbbf38c335bfb98d80e5b09db956e3f0c5

**Comment by Privatecoder** [comment]
works fine now (proxied)
