### ISSUE TITLE
Listen to port on HassOS outside ingress

### ISSUE THREAD

**Issue by jumpingmushroom** [matt8707/addon-ha-fusion#9]
Hi! First off, thanks for a fantastic dashboard and addon. Easy to use as well as snappy as hell to configure.

I would however like to show this on my hallway dashboard using fully kiosk browser. Loading it from the sidebar works, but I would really appreciate if you could add a configuration option for the addon that allows to specify a host port to listen to. That way port 8099 could be exposed on the HassOS host and be opened as a separate web page.

Thanks

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/issues/171

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/releases/tag/2024.1.6
